  
# █▀▀ █▀▀▄ █░█ ▀█░█▀ █  #
# █▀▀ █░░█ █▀▄ ░█▄█░ ▀  #
# ▀▀▀ ▀▀▀░ ▀░▀ ░░▀░░ ▄  #

################
### MONITORS ###
################

monitor=,1366x768@60,auto,1

###############
### DEFAULT ###
###############

# Programs
$terminal = alacritty
$fileManager = nautilus
$browser = brave
$menu = rofi -show drun

$wa = flatpak run com.rtosta.zapzap

# Themes
$cursor-theme = Capitaine-cursors
$cursor-size = 20
$icon-theme = Gruvbox-Dark
$gtk-theme = Gruvbox-Teal-Dark

############
### MISC ###
############

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}

###############
### SOURCES ###
###############

source = ~/.config/hypr/src/startup.conf
source = ~/.config/hypr/src/env.conf
source = ~/.config/hypr/src/display.conf
source = ~/.config/hypr/src/animations.conf
source = ~/.config/hypr/src/input.conf
source = ~/.config/hypr/src/keybinds.conf
source = ~/.config/hypr/src/winrules.conf
