[general]

import = [ "~/.config/alacritty/themes/gruvbox_dark.toml" ]

[window]

opacity = 1
blur = true
padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 10

[cursor.style]

shape = "Underline"
blinking = "Always"
